# Generated by Django 2.2.10 on 2020-04-01 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablaaulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(max_length=20)),
                ('nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tabla.tablaregistros')),
            ],
        ),
    ]
