# Generated by Django 2.2.10 on 2020-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla', '0002_tablaaulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaregistros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
